# Generated by Django 4.2.16 on 2026-06-07 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('meeting_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('fyear', models.IntegerField()),
                ('meeting_minutes', models.FileField(blank=True, null=True, upload_to='')),
                ('meeting_invite', models.FileField(blank=True, null=True, upload_to='')),
                ('is_agm_sent', models.BooleanField(default=False)),
                ('is_minutes_sent', models.BooleanField(default=False)),
                ('is_init', models.BooleanField(default=False)),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('oc_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.ocmaster')),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OwnerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('msg_subject', models.CharField(max_length=100)),
                ('msg_body', models.CharField(max_length=2000)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('mail_status', models.CharField(choices=[('prepared', 'prepared'), ('sending', 'sending'), ('sent', 'sent'), ('fail', 'fail'), ('na', 'na')], default='prepared', max_length=20)),
                ('category', models.CharField(choices=[('certificate', 'OC certificate request'), ('key', 'Key and Fob request'), ('issue', 'Issue report '), ('other', 'Other')], default='certificate', max_length=20)),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('lot_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.lot')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('policy_num', models.CharField(max_length=100)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('broker', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('premium_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('premium_due_date', models.DateField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=5, null=True)),
                ('base_premium', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('est_commission', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('actual_commission', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('common_contents', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('policy_kind', models.CharField(default='Residential Strata', max_length=50)),
                ('building_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('public_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('building_covered', models.CharField(default='see more details in the Certificate of Currency', max_length=50)),
                ('terrorism_covered', models.CharField(blank=True, max_length=50, null=True)),
                ('loss_rent', models.CharField(blank=True, max_length=50, null=True)),
                ('liability', models.CharField(blank=True, max_length=50, null=True)),
                ('voluntary_worker', models.CharField(blank=True, max_length=50, null=True)),
                ('fidelity_guarantee', models.CharField(blank=True, max_length=50, null=True)),
                ('office_bearers', models.CharField(blank=True, max_length=50, null=True)),
                ('gov_audit_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('appeal_exp', models.CharField(blank=True, max_length=50, null=True)),
                ('legal_def', models.CharField(blank=True, max_length=50, null=True)),
                ('fixture_improve', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_cert', models.FileField(blank=True, null=True, upload_to='')),
                ('excess', models.IntegerField(default=0)),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgmDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('seq_no', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(blank=True, max_length=1500, null=True)),
                ('is_insurance', models.BooleanField(default=False)),
                ('agm_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strata.agm')),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
            options={
                'ordering': ['seq_no'],
            },
        ),
    ]
