"""
Django settings for my_project project.
Generated by 'django-admin startproject' using Django 2.2.
For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys

from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(BASE_DIR, 'my_project', 'templates')
STATIC_DIR = os.path.join(BASE_DIR, "static")
sys.path.append(os.path.join(BASE_DIR, 'static', 'python'))

# Ensure the project root is importable so top-level packages like `scripts`
# resolve regardless of how the WSGI app is launched (e.g. Vercel serverless).
sys.path.append(BASE_DIR)
sys.path.append(os.path.join(BASE_DIR, 'my_project'))
sys.path.append(STATIC_DIR)
sys.path.append(TEMPLATES_DIR)

# Set SECRET_KEY via environment variable in Vercel / production
SECRET_KEY = os.environ.get('SECRET_KEY', 'fallback-dev-key-replace-in-vercel-env')

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['47.74.86.36', 'portal.topocs.com.au', '.vercel.app', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    'crispy_bootstrap4',
    'strata',
    'base',
    'property',
    'finance',
    'django_apscheduler',
    'mathfilters',
    'widget_tweaks',

    # 'users.apps.UsersConfig',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Django 3.2+ requires an explicit default primary key type. Keep AutoField to
# match the existing schema and avoid generating new migrations.
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


def _env(name, default=''):
    """Read an env var and strip stray whitespace/newlines that can sneak in
    when values are pasted into a dashboard (a leading tab in DB_HOST, for
    example, breaks DNS resolution)."""
    return os.environ.get(name, default).strip()


# Prefer a single DATABASE_URL when provided (the format Railway / PlanetScale /
# most managed MySQL hosts hand you, e.g.
# mysql://user:pass@host:3306/dbname). Fall back to the discrete DB_* vars.
DATABASE_URL = _env('DATABASE_URL')
if DATABASE_URL:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=0,
            ssl_require=_env('DB_SSL_REQUIRE', 'False') == 'True',
        ),
    }
    DATABASES['default']['ENGINE'] = 'django.db.backends.mysql'
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': _env('DB_NAME', 'strata'),
            'USER': _env('DB_USER', 'capconnex_db_user'),
            'PASSWORD': _env('DB_PASSWORD', ''),
            'HOST': _env('DB_HOST', 'rm-j0b9z69u968t7av0yuo.mysql.australia.rds.aliyuncs.com'),
            'PORT': _env('DB_PORT', '3306'),
        }
    }

MAIL_CONFIG = {
    'USER': os.environ.get('MAIL_USER', 'info@topocs.com.au'),
    'PASSWORD': os.environ.get('MAIL_PASSWORD', ''),
    'PORT': int(os.environ.get('MAIL_PORT', '465')),
    'SMTP': os.environ.get('MAIL_SMTP', 'cp-wc59.per01.ds.network'),
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
DATE_FORMAT = 'j M Y'

LANGUAGE_CODE = 'en-us'
CONN_MAX_AGE = None

TIME_ZONE = 'Australia/Melbourne'

USE_I18N = True

USE_L10N = False

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [STATIC_DIR]

# Serve static files via WhiteNoise straight from the staticfiles finders, so a
# `collectstatic` step is not required (Vercel's @vercel/python has no build
# hook for it). Use the NON-manifest storage backend: the manifest variant
# raises "Missing staticfiles manifest entry" on every {% static %} call when
# collectstatic has not run, which would 500 every page.
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
# On serverless the project filesystem is read-only; only /tmp is writable.
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

LOGIN_URL = 'base:login'
INVOICE_TEMPLATE = 'invoice.html'
RECEIPT_TEMPLATE = 'cash_receipt.html'
MAIL_ADDRESS = 'info@topocs.com.au'
AGM_TEMPLATE = 'agm_meeting_invite.html'
AGM_BUDGET_TEMPLATE = 'agm_budget_nomination.html'

MESSAGE_TAGS = {
    messages.DEBUG: 'info',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'ERROR'),
        },
    },
}

INSURANCE_DAY = 45
