from django.urls import path

from . import views as p_view

app_name = 'finance'

# path('property/create', p_view.PropertyCreateView.as_view(), name='property_create'),
urlpatterns = [
    path('coa/', p_view.COAListView.as_view(), name='coa_list'),
    path('coa/create', p_view.COACreateView.as_view(), name='coa_create'),
    path('coa/delete', p_view.coa_delete, name='coa_delete'),
    path('coa/update/<int:pk>', p_view.COAUpdateView.as_view(), name='coa_update'),
    path('inc/', p_view.IncListView.as_view(), name='inc_list'),
    path('inc/create', p_view.IncCreateView.as_view(), name='inc_create'),
    path('inc/delete', p_view.inc_delete, name='inc_delete'),
    path('inc/update/<int:pk>', p_view.IncUpdateView.as_view(), name='inc_update'),
    path('supply/', p_view.SupplierListView.as_view(), name='supply_list'),
    path('gl/', p_view.GLsListView.as_view(), name='gl_list'),
    path('glrecon/', p_view.GLsReconListView.as_view(), name='gl_recon_list'),
    path('gl/recon', p_view.gl_recon, name='gl_recon'),
    path('bank/recon', p_view.bank_recon, name='bank_recon'),
    path('bank/upload', p_view.bank_upload, name='bank_upload'),
    path('supply/create', p_view.SupplierCreateView.as_view(), name='supply_create'),
    path('supply/delete', p_view.supply_delete, name='supply_delete'),
    path('supply/update/<int:pk>', p_view.SupplierUpdateView.as_view(), name='supply_update'),
    path('invoice/', p_view.InvoiceListView.as_view(), name='invoice_list'),
    path('invoice/create', p_view.InvoiceCreateView.as_view(), name='invoice_create'),
    path('invoice/delete', p_view.invoice_delete, name='invoice_delete'),
    path('invoice/cancel', p_view.cancel_invoice, name='invoice_cancel'),
    path('invoice/fullpay', p_view.pay_invoice, name='invoice_full_pay'),
    path('invoice/partpay', p_view.part_pay_invoice, name='invoice_part_pay'),
    path('invoice/update/<int:pk>', p_view.InvoiceUpdateView.as_view(), name='billing_update'),
    path('billing/', p_view.BillingListView.as_view(), name='billing_list'),
    path('billing/partpay', p_view.part_pay_bill, name='billing_part_pay'),
    path('billing/special', p_view.special_levy, name='billing_special_levy'),
    path('billing/create', p_view.BillingCreateView.as_view(), name='billing_create'),
    path('billing/delete', p_view.billing_delete, name='billing_delete'),
    path('billing/confirm', p_view.billing_pay, name='billing_confirm'),
    path('billing/resend', p_view.billing_resend, name='billing_resend'),
    path('billing/remind', p_view.billing_remind, name='billing_remind'),
    path('billing/reset', p_view.billing_reset, name='billing_reset'),
    path('billing/update/<int:pk>', p_view.BillingUpdateView.as_view(), name='billing_update'),
    path('billing/pdf/<int:pk>', p_view.Invoice2Pdf.as_view(), name='invoice_pdf'),
    path('cash/pdf/<int:pk>', p_view.CashReceipt2Pdf.as_view(), name='cash_pdf'),
    path('billing/pdflatest/<int:pk>', p_view.LastestInvoice2Pdf.as_view(), name='invoice_pdf_raw'),
    path('billing/pdfgen/<int:pk>', p_view.GetOcData.as_view(), name='invoice_pdf_gen'),
    path('oc_cert/', p_view.OcCertListView.as_view(), name='oc_cert_list'),
    path('fs/', p_view.FSListView.as_view(), name='fs_list'),
    # path('oc_cert/create', p_view.OcCertCreateView.as_view(), name='oc_cert_create'),
    path('oc_cert/create', p_view.oc_cert_create, name='oc_cert_create'),
    path('oc_cert/update/<int:pk>', p_view.OcCertUpdateView.as_view(), name='oc_cert_update'),
    path('oc_cert/pdf/<int:pk>', p_view.Oc2Pdf.as_view(), name='oc_pdf'),
    # TODO to be removed
    path('oc_cert/view/<int:pk>', p_view.GetOcData.as_view(), name='oc_data'),
    path('fs/create', p_view.FSCreateView.as_view(), name='fs_create'),
    path('fs/update/<int:pk>', p_view.FSUpdateView.as_view(), name='fs_update'),
    path('fs/owner/delete', p_view.fs_del, name='fs_owner'),
    path('fs/owner', p_view.fs_owner, name='fs_owner'),
    path('fs/pdf/<int:pk>', p_view.Fs2Pdf.as_view(), name='fs_pdf'),
    path('gl/new', p_view.generate_gl, name='gl_create'),
    path('gl/export', p_view.gl_export, name='gl_export'),
    path('bank/', p_view.BankListView.as_view(), name='bank_list'),
    path('clientledger/', p_view.ClientLedgerListView.as_view(), name='client_ledger_list'),
    path('ajax/getdefer/', p_view.get_defer_ind, name='get_defer'),
    path('cash/', p_view.CashRecpListView.as_view(), name='cash_list'),
    path('cash/cancel', p_view.cash_cancel, name='cash_cancel'),
    path('ajax/getbanktrans', p_view.get_bank_trans_detail, name='bank_detail'),
    path('ajax/manualcash', p_view.allocate_cash, name='manual_cash'),
    path('ajax/billing/cancel', p_view.billing_cancel, name='cancel_bill'),
    path('occert/ajax/create', p_view.oc_cert_handle, name='oc_cert_handle'),

]
