"""
agm notice master interface, following documents need to be consolidated.
1. agm notice + agenda (generated by application)
2. last year AGM minutes
3. insurance certificate
4. FS
5. budget and revenue documents
6. proxy form (static template but needs to add plan number and oc description
"""
from base.models import Client
from my_project import settings
from property.models import Property, OCMaster
from scripts.PDF_service.pdf import agm_pdf_to_file
from scripts.PDF_service.pdf_generator import merge_pdf_files
from scripts.agm.agm_fs_generate import agm_generate_fs
from scripts.agm.budget import AgmOCBudget
from strata.models import AgmDetail


def generate_agm_pdf(agm_item):
    agm_urls = []
    client = Client.objects.get(pk=1)
    agendas = AgmDetail.objects.filter(agm_ref_id=agm_item.id)
    property = Property.objects.get(pk=agm_item.property_id)
    oc = OCMaster.objects.get(pk=agm_item.oc_id)

    invite_context = {'agm': agm_item.agm,
                      'insurance': agm_item.insurance,
                      'property': property,
                      'oc': oc,
                      "client": client,
                      "agendas": agendas}

    filename = str(agm_item.id) + "meeting_invite.pdf"
    meeting_url = agm_pdf_to_file(settings.AGM_TEMPLATE, invite_context, filename, '/css/agm.css')
    agm_urls.append(meeting_url)

    # append last year agm media/invoice-6.pdf

    agm_urls.append(agm_item.last_agm.meeting_minutes.path)
    # append insurance certificate
    agm_urls.append(agm_item.insurance.currency_cert.path)

    # financial statement, check fs exists, create a new one if it doesn't
    fs_url = agm_generate_fs(agm_item)
    agm_urls.append(fs_url)

    # budget and revenue docs
    agm_budget = AgmOCBudget(agm_item.oc_id, agm_item.fyear)
    budget_context = agm_budget.get_context()
    filename = str(agm_item.id) + 'budget.pdf'
    budget_url = agm_pdf_to_file(settings.AGM_BUDGET_TEMPLATE, budget_context, filename, '/css/agm.css')
    agm_urls.append(budget_url)

    # proxy form
    agm_urls.append(settings.STATIC_DIR + '/agm/proxyform.pdf')

    # combine pdfs all together
    filename = "AGM_" + str(agm_item.fyear) + "-" + str(agm_item.id) + ".pdf"
    amg_pdf_path = merge_pdf_files(agm_urls, filename)

    return amg_pdf_path

    # send notifcaiton
