# Generated by Django 4.2.16 on 2026-06-07 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('client_name', models.CharField(max_length=255, verbose_name='client name')),
                ('ABN', models.CharField(blank=True, max_length=100)),
                ('TFN', models.CharField(blank=True, max_length=50)),
                ('Address', models.CharField(blank=True, max_length=500)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('post_adr', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('data_src', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('filetype', models.CharField(choices=[('EXCEL', 'EXCEL')], default='EXCEL', max_length=10)),
                ('sheet_mode', models.CharField(choices=[('ALL', 'ALL'), ('MATCH', 'MATCH'), ('SINGLE', 'SINGLE')], default='ALL', max_length=20)),
                ('sheet_name', models.CharField(blank=True, max_length=100)),
                ('db_table', models.CharField(max_length=100)),
                ('client_ref', models.ForeignKey(db_column='client_ref', on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('staff', 'Staff'), ('owner', 'Owner'), ('manager', 'Manager'), ('committee', 'Committee Member')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('acc_code', models.CharField(max_length=100)),
                ('acc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('beg_bal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('end_bal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('period', models.CharField(max_length=20, null=True)),
                ('client_ref', models.ForeignKey(db_column='client_ref', on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('seq_prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('seq_code', models.CharField(max_length=100, unique=True)),
                ('seq_num', models.BigIntegerField(default=0)),
                ('seq_category', models.CharField(blank=True, max_length=100, null=True)),
                ('seq_char_width', models.IntegerField()),
                ('version', models.BigIntegerField(default=0)),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cc', models.CharField(blank=True, max_length=100, null=True)),
                ('msg_subject', models.CharField(max_length=100)),
                ('msg_body', models.CharField(max_length=2000)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('read_status', models.CharField(default='unread', max_length=20)),
                ('mail_status', models.CharField(choices=[('prepared', 'prepared'), ('sending', 'sending'), ('sent', 'sent'), ('fail', 'fail'), ('na', 'na')], default='prepared', max_length=20)),
                ('category', models.CharField(choices=[('email', 'email'), ('note', 'note'), ('email-note', 'email-note'), ('working-order', 'working-order')], default='note', max_length=20)),
                ('property_id', models.IntegerField(default=0)),
                ('oc_id', models.IntegerField(default=0)),
                ('lot', models.CharField(blank=True, max_length=50, null=True)),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('status', models.CharField(choices=[('01', 'Success'), ('02', 'Fail'), ('03', 'In progress')], max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('src_ref', models.ForeignKey(db_column='src_ref', on_delete=django.db.models.deletion.CASCADE, to='base.datasource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('error_code', models.CharField(max_length=50)),
                ('error_type', models.CharField(choices=[('error', 'error'), ('warning', 'warning'), ('info', 'info')], max_length=50)),
                ('error_message', models.CharField(blank=True, max_length=300, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSourceRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('src_header', models.CharField(max_length=200)),
                ('ftype', models.CharField(choices=[('string', 'string'), ('number', 'number'), ('cal', 'calculation'), ('date', 'date')], default='string', max_length=10)),
                ('cal_exp', models.CharField(blank=True, max_length=100)),
                ('map_field', models.CharField(blank=True, max_length=100)),
                ('is_trans', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('reg_exp', models.CharField(blank=True, max_length=255)),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('src_ref', models.ForeignKey(db_column='src_ref', on_delete=django.db.models.deletion.CASCADE, to='base.datasource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
