# Generated by Django 4.2.16 on 2026-06-07 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('lot', models.CharField(max_length=50)),
                ('type_lot', models.CharField(blank=True, max_length=50, null=True)),
                ('module_type', models.CharField(choices=[('residential', 'residential'), ('commercial', 'commercial')], default='residential', max_length=50)),
                ('billing_adr', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_adr', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_name1', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('agent_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tenant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('prefer_mail', models.CharField(choices=[('owner', 'owner'), ('agent', 'agent')], default='owner', max_length=20)),
                ('general_mail', models.CharField(choices=[('owner', 'owner'), ('agent', 'agent')], default='owner', max_length=20)),
                ('is_committee', models.BooleanField(default=False)),
                ('unit_no', models.CharField(blank=True, max_length=30, null=True)),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('lots_num', models.BigIntegerField()),
                ('total_lot_liability', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_lot_entitle', models.DecimalField(decimal_places=2, max_digits=20)),
                ('street', models.CharField(max_length=200)),
                ('suburb', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('post_code', models.CharField(max_length=10)),
                ('country', models.CharField(blank=True, default='Australia', max_length=200, null=True)),
                ('ABN', models.CharField(blank=True, max_length=200, null=True)),
                ('TFN', models.CharField(blank=True, max_length=200, null=True)),
                ('GST_register', models.BooleanField(default=False)),
                ('plan_num', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rel_act', models.CharField(blank=True, max_length=200, null=True)),
                ('module_type', models.CharField(blank=True, max_length=50, null=True)),
                ('init_period', models.BooleanField(default=False)),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OCMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('manager_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_sign', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('seal', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('manager_threshold', models.IntegerField(default=0)),
                ('chairman_threshold', models.IntegerField(default=0)),
                ('BSB', models.CharField(blank=True, max_length=20, null=True)),
                ('Account', models.CharField(blank=True, max_length=50, null=True)),
                ('Account_name', models.CharField(blank=True, max_length=130, null=True)),
                ('beg_bal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('frequency', models.CharField(choices=[('Quarterly', 'quarter'), ('Monthly', 'month'), ('Half yearly', 'half year'), ('Annual', 'annual')], max_length=20)),
                ('billing_start_date', models.DateField()),
                ('liability', models.IntegerField(default=0)),
                ('bank_fee', models.IntegerField(default=10)),
                ('biller_code', models.CharField(blank=True, max_length=50, null=True)),
                ('oc_rule', models.FileField(blank=True, null=True, upload_to='')),
                ('meeting_mins', models.FileField(blank=True, null=True, upload_to='')),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OcBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('fin_year', models.IntegerField()),
                ('acc_code', models.CharField(max_length=20)),
                ('acc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('oc_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.ocmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LotOCMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createby', models.CharField(default=' ', max_length=50)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updateby', models.CharField(default=' ', max_length=50)),
                ('updatetime', models.DateField(auto_now=True)),
                ('entitlement', models.DecimalField(decimal_places=2, max_digits=20)),
                ('liability', models.DecimalField(decimal_places=2, max_digits=20)),
                ('CRN', models.CharField(blank=True, max_length=100, null=True)),
                ('client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('lot_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.lot')),
                ('oc_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.ocmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='property_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='lot',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
